"""Generate frozen, schema-valid contract fixtures for Persons 1-3.

Deterministic: fixed IDs, fixed timestamps, and boxes measured from the committed demo clip.
Reconstruction artifacts here are CONTRACT MOCKS (pixel copies with recorded translations), not
Probity output; they exist so the UI/report/provenance consumers can build independently.

Usage: uv run python scripts/generate_contract_fixtures.py
"""

from __future__ import annotations

import hashlib
import io
import json
import subprocess
from fractions import Fraction
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image

from probity.domain.enums import (
    AlignmentMethod,
    AssetKind,
    CaseStatus,
    ErrorCode,
    ExplanationSource,
    IndexState,
    InferenceMode,
    IngestState,
    Interpolation,
    JobKind,
    JobStage,
    JobState,
    Legibility,
    ObservationSource,
    OperatingMode,
    PolicyOutcome,
    PolicyStage,
    ReasonCode,
    ReconstructionState,
    ReviewDecision,
    RigidSubjectKind,
    SearchStatus,
    SourceRole,
    SubjectType,
    TrackState,
    VetoReason,
    VisibilityKind,
)
from probity.domain.fixtures import (
    FixtureCatalog,
    FixtureFile,
    FixtureManifest,
    FixtureModelRef,
    FixtureSource,
)
from probity.domain.ids import canonical_json, frame_id, segment_id
from probity.domain.models import (
    AssetRef,
    CaseWorkspace,
    ClassConfidence,
    CoverageCounts,
    CoveragePct,
    Detection,
    EvidenceReport,
    FrameManifest,
    FrameManifestEntry,
    HumanReview,
    IntegrityScore,
    JobError,
    JobView,
    ObservedAction,
    PartialCoverage,
    PixelOrigin,
    PixelProvenance,
    PolicyDecision,
    ProvenanceSummary,
    ReconstructionRun,
    RigidSubjectObservation,
    ScoreComponents,
    SearchCandidate,
    SearchEvidence,
    SearchPlan,
    SearchResult,
    SegmentDescription,
    SourceLutEntry,
    SourceVideo,
    TimeRangeUs,
    Track,
    TrackObservation,
    VideoSegment,
    VisibilityLimit,
    integrity_score_0_100,
)
from probity.domain.policy import default_policy
from probity.domain.prompts import COSMOS_INGESTION_PROMPT_SHA256

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "fixtures/demo/source/demo-plate-90s.mp4"
OUT = ROOT / "fixtures/contracts"
ART = OUT / "artifacts"

BASE_MS = 1_791_561_600_000  # 2026-10-09T16:00:00Z
FIXTURE_ID = "demo-plate-90s"
COSMOS_MODEL = "fixture/cosmos-reason-describe-v1"
EMBED_MODEL = "fixture/cosmos-embed-v1"
YOLO_MODEL = "fixture/yolov8n-plate-sign-v1"
PLANNER_MODEL = "fixture/wandb-planner-v1"
REASONER_MODEL = "fixture/wandb-explainer-v1"
LICENSE = (
    "Synthetic clip generated by scripts/generate_demo_video.py; no real people, places, or plates."
)


def det_uuid7(label: str, offset_ms: int = 0) -> str:
    digest = hashlib.sha256(label.encode()).digest()
    raw = bytearray((BASE_MS + offset_ms).to_bytes(6, "big") + digest[:10])
    raw[6] = 0x70 | (raw[6] & 0x0F)
    raw[8] = 0x80 | (raw[8] & 0x3F)
    h = raw.hex()
    return f"{h[:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:]}"


def ts(offset_s: float) -> str:
    whole = int(offset_s)
    micros = round((offset_s - whole) * 1_000_000)
    h, rem = divmod(16 * 3600 + whole, 3600)
    m, s = divmod(rem, 60)
    return f"2026-10-09T{h:02d}:{m:02d}:{s:02d}.{micros:06d}Z"


def fake_sha(label: str) -> str:
    return hashlib.sha256(f"probity-contract-mock:{label}".encode()).hexdigest()


def file_sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def dump(name: str, payload: Any) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    data: Any
    if isinstance(payload, list):
        data = [p.model_dump(mode="json") for p in payload]
    else:
        data = payload.model_dump(mode="json")
    (OUT / name).write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


# ------------------------------------------------------------------------------------------
# Media facts measured from the committed clip
# ------------------------------------------------------------------------------------------


def ffprobe_frames() -> tuple[str, list[dict[str, Any]], str]:
    out = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_frames",
            "-show_entries",
            "frame=pts,best_effort_timestamp,key_frame,width,height:stream=time_base",
            "-of",
            "json",
            str(SOURCE),
        ],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    data = json.loads(out)
    version = subprocess.run(
        ["ffprobe", "-version"], check=True, capture_output=True, text=True
    ).stdout.splitlines()[0]
    return data["streams"][0]["time_base"], data["frames"], version


def decode_frame(n: int) -> np.ndarray:
    png = subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-i",
            str(SOURCE),
            "-vf",
            f"select=eq(n\\,{n})",
            "-fps_mode",
            "passthrough",
            "-frames:v",
            "1",
            "-f",
            "image2pipe",
            "-vcodec",
            "png",
            "-",
        ],
        check=True,
        capture_output=True,
    ).stdout
    return np.array(Image.open(io.BytesIO(png)).convert("RGB"))


def plate_bbox(img: np.ndarray) -> tuple[int, int, int, int]:
    region = img[380:540]
    mask = (region > 225).all(axis=2)
    ys, xs = np.nonzero(mask)
    return int(xs.min()), int(ys.min()) + 380, int(xs.max()) + 1, int(ys.max()) + 381


def main() -> None:
    policy = default_policy()
    source_sha = file_sha(SOURCE)
    byte_length = SOURCE.stat().st_size
    time_base, frames, ffprobe_version = ffprobe_frames()
    tb = Fraction(time_base)

    case_id = det_uuid7("case")
    video_id = det_uuid7("video", 1_000)
    storage_uri = f"source/sha256/{source_sha[:2]}/{source_sha}/original.mp4"

    def pts_us(n: int) -> int:
        f = frames[n]
        raw = f.get("pts", f.get("best_effort_timestamp"))
        return (raw * tb.numerator * 1_000_000) // tb.denominator

    entries = []
    for i, f in enumerate(frames):
        raw = f.get("pts", f.get("best_effort_timestamp"))
        entries.append(
            FrameManifestEntry(
                frame_number=i,
                pts_us=pts_us(i),
                pts=raw,
                is_keyframe=bool(f["key_frame"]),
                width_px=f["width"],
                height_px=f["height"],
            )
        )
    frame_count = len(entries)
    end_ticks = entries[-1].pts + (entries[-1].pts - entries[-2].pts)
    duration_us = (end_ticks * tb.numerator * 1_000_000) // tb.denominator
    manifest = FrameManifest.create(
        created_at=ts(2),
        video_id=video_id,
        source_sha256=source_sha,
        time_base=time_base,
        extractor=ffprobe_version,
        frames=tuple(entries),
    )
    dump("frame_manifest.json", manifest)

    asset_source = det_uuid7("asset:source", 1_100)
    probe_sha = fake_sha("probe")
    common_video = dict(
        video_id=video_id,
        case_id=case_id,
        original_name="demo-plate-90s.mp4",
        sha256=source_sha,
        byte_length=byte_length,
        mime="video/mp4",
        container="mp4",
        video_codec="h264",
        width_px=1280,
        height_px=720,
        duration_us=duration_us,
        time_base=time_base,
        nominal_fps="30/1",
        frame_count=frame_count,
        has_audio=False,
        storage_uri=storage_uri,
        source_asset_uri=f"asset://{asset_source}",
        probe_sha256=probe_sha,
        license_note=LICENSE,
        fixture_id=FIXTURE_ID,
    )
    case = CaseWorkspace.create(
        created_at=ts(0),
        case_id=case_id,
        display_name="Fictional Case 0420 (demo)",
        mode=OperatingMode.AUTO,
        owner_alias="analyst-1",
        status=CaseStatus.ACTIVE,
    )
    dump("case_workspace.json", case)

    # ---------------- segments (8 s windows, 2 s overlap) ----------------
    def first_frame_at_or_after(us: int) -> int:
        return next(e.frame_number for e in entries if e.pts_us >= us)

    def last_frame_before(us: int) -> int:
        return max(e.frame_number for e in entries if e.pts_us < us)

    windows: list[tuple[int, int]] = []
    start = 0
    while True:
        end = min(start + policy.segment.duration_us, duration_us)
        windows.append((start, end))
        if end >= duration_us:
            break
        start += policy.segment.step_us

    S = 1_000_000
    seg_text: list[dict[str, Any]] = [
        dict(
            d="Empty two-lane road under even daylight; static camera; no vehicles or signs visible.",
            terms=("road", "empty", "static camera"),
            vis=(VisibilityKind.CLEAR,),
        ),
        dict(
            d="A blue sedan enters from the left near 00:10.0 moving left-to-right; a white rear plate region is visible but only partly legible at this resolution.",
            terms=("blue sedan", "car", "license plate", "rear plate", "left-to-right"),
            vis=(VisibilityKind.LOW_RESOLUTION,),
            cls=(("car", 0.91, 6), ("license_plate", 0.74, 4)),
        ),
        dict(
            d="The blue sedan crosses mid-frame left-to-right; its white rear plate is most visible between 00:12 and 00:16 and remains partly legible.",
            terms=(
                "blue sedan",
                "car",
                "license plate",
                "rear plate",
                "most visible",
                "left-to-right",
            ),
            vis=(VisibilityKind.LOW_RESOLUTION, VisibilityKind.COMPRESSION),
            cls=(("car", 0.94, 8), ("license_plate", 0.81, 7)),
        ),
        dict(
            d="The blue sedan approaches the right edge and exits the frame near 00:22.",
            terms=("blue sedan", "car", "exits right"),
            vis=(VisibilityKind.CLEAR,),
            cls=(("car", 0.88, 4), ("license_plate", 0.52, 1)),
        ),
        dict(
            d="Empty road; no vehicles or signs visible.",
            terms=("road", "empty"),
            vis=(VisibilityKind.CLEAR,),
        ),
        dict(
            d="Empty road; no vehicles or signs visible.",
            terms=("road", "empty"),
            vis=(VisibilityKind.CLEAR,),
        ),
        dict(
            d="A red van enters from the right near 00:40 moving right-to-left; its rear plate area is covered by a gray rectangle.",
            terms=("red van", "truck", "right-to-left", "plate obstructed"),
            vis=(VisibilityKind.OCCLUSION,),
            cls=(("truck", 0.86, 4),),
        ),
        dict(
            d="The red van crosses right-to-left; a gray rectangle occludes the plate region, which is illegible.",
            terms=("red van", "truck", "plate obstructed", "occlusion", "right-to-left"),
            vis=(VisibilityKind.OCCLUSION,),
            cls=(("truck", 0.92, 8), ("license_plate", 0.31, 2)),
        ),
        dict(
            d="The red van exits the left edge near 00:52; the road is then empty.",
            terms=("red van", "truck", "exits left"),
            vis=(VisibilityKind.OCCLUSION,),
            cls=(("truck", 0.83, 3),),
        ),
        dict(
            d="Empty road; a green rectangular sign appears in the upper right near 00:60.",
            terms=("green sign", "sign", "upper right"),
            vis=(VisibilityKind.CLEAR,),
            cls=(("sign", 0.77, 2),),
        ),
        dict(
            d="A static green rectangular sign with five white marks is visible in the upper right; the marks are not legible as characters.",
            terms=("green sign", "sign", "white marks", "static"),
            vis=(VisibilityKind.LOW_RESOLUTION,),
            cls=(("sign", 0.89, 8),),
        ),
        dict(
            d="The static green sign remains visible in the upper right; no vehicles visible.",
            terms=("green sign", "sign", "static"),
            vis=(VisibilityKind.CLEAR,),
            cls=(("sign", 0.87, 8),),
        ),
        dict(
            d="The green sign disappears near 00:75; the scene darkens from about 00:78.",
            terms=("green sign", "sign", "lighting change", "darkening"),
            vis=(VisibilityKind.DARKNESS,),
            cls=(("sign", 0.71, 3),),
        ),
        dict(
            d="The whole scene is darker between 00:78 and 00:84, reducing visibility; lighting returns to normal afterwards.",
            terms=("lighting change", "dark", "low visibility"),
            vis=(VisibilityKind.DARKNESS,),
        ),
        dict(
            d="Empty road under normal lighting until the end of the clip.",
            terms=("road", "empty"),
            vis=(VisibilityKind.CLEAR,),
        ),
    ]
    assert len(seg_text) == len(windows), (len(seg_text), len(windows))

    # ---------------- detections over the plate track window ----------------
    det_frames = list(range(405, 430, 3))
    detections: list[Detection] = []
    measured: dict[int, tuple[int, int, int, int]] = {}
    for n in det_frames:
        bbox = plate_bbox(decode_frame(n))
        measured[n] = bbox
        conf = round(0.70 + 0.02 * (4 - abs(n - 417) // 3), 2)
        detections.append(
            Detection.create(
                created_at=ts(30),
                detection_id=det_uuid7(f"det:plate:{n}", 30_000),
                video_id=video_id,
                frame_id=frame_id(video_id, n),
                pts_us=pts_us(n),
                model_id=YOLO_MODEL,
                model_sha256=fake_sha("yolo-weights"),
                class_id=0,
                class_name="license_plate",
                confidence=conf,
                bbox_px=bbox,
                bbox_norm=tuple(
                    round(v / d, 6) for v, d in zip(bbox, (1280, 720, 1280, 720), strict=True)
                ),
                occlusion_score=0.0,
                inference_mode=InferenceMode.FIXTURE,
            )
        )
    for n in (417, 424):
        measured.setdefault(n, plate_bbox(decode_frame(n)))
    measured[409] = plate_bbox(decode_frame(409))
    dump("detections.json", detections)
    det_by_frame = {int(d.frame_id.rsplit(":f", 1)[1]): d for d in detections}

    segments: list[VideoSegment] = []
    descriptions: list[SegmentDescription] = []
    assets: list[AssetRef] = []
    for i, ((s0, s1), meta) in enumerate(zip(windows, seg_text, strict=True)):
        sid = segment_id(video_id, i)
        thumb_id = det_uuid7(f"asset:thumb:{i}", 20_000 + i)
        sf, ef = (
            first_frame_at_or_after(s0),
            last_frame_before(s1) if s1 < duration_us else frame_count - 1,
        )
        thumb_frame = (sf + ef) // 2
        assets.append(
            AssetRef(
                asset_id=thumb_id,
                case_id=case_id,
                kind=AssetKind.THUMBNAIL,
                storage_uri=f"derived/{video_id}/thumbnail/{sid}/thumb.jpg",
                media_type="image/jpeg",
                byte_length=24_000 + i,
                sha256=fake_sha(f"thumb:{i}"),
                non_evidentiary=True,
                created_at=ts(20),
            )
        )
        ev_ids = tuple(d.detection_id for n, d in det_by_frame.items() if s0 <= d.pts_us < s1)
        cls = tuple(
            ClassConfidence(class_name=c, max_confidence=conf, detection_count=count)
            for c, conf, count in meta.get("cls", ())
        )
        segments.append(
            VideoSegment.create(
                created_at=ts(40 + i),
                segment_id=sid,
                video_id=video_id,
                source_sha256=source_sha,
                ordinal=i,
                start_pts_us=s0,
                end_pts_us=s1,
                start_frame=sf,
                end_frame=ef,
                thumbnail_uri=f"asset://{thumb_id}",
                thumbnail_frame=thumb_frame,
                description=meta["d"],
                description_model_id=COSMOS_MODEL,
                search_terms=meta["terms"],
                detected_classes=cls,
                visibility_tags=meta["vis"],
                evidence_detection_ids=ev_ids,
                uncertainty=("Fixture description; plate characters are not quoted.",)
                if cls
                else (),
                embedding_ref=f"{FIXTURE_ID}/embeddings.npy#{i}",
                embedding_model_id=EMBED_MODEL,
                embedding_dimension=64,
                index_state=IndexState.INDEXED,
                mode=InferenceMode.FIXTURE,
            )
        )
        subjects = ()
        if i in (1, 2):
            subjects = (
                RigidSubjectObservation(
                    kind=RigidSubjectKind.LICENSE_PLATE,
                    color="white",
                    location="rear of blue sedan, lower left of vehicle",
                    approximate_size="about 76x26 px",
                    orientation="fronto-parallel",
                    legibility=Legibility.PARTIAL,
                    quoted_text=None,
                    uncertainty="Dark glyph marks are visible but no character is resolvable.",
                    has_multiple_clearer_observations=True,
                    confidence=0.78,
                    time_range=TimeRangeUs(
                        start_pts_us=max(s0, 10 * S), end_pts_us=min(s1, 16 * S)
                    ),
                ),
            )
        actions = ()
        if i in (1, 2, 3):
            actions = (
                ObservedAction(
                    description="blue sedan moves across frame",
                    direction="left-to-right",
                    confidence=0.9,
                    time_range=TimeRangeUs(
                        start_pts_us=max(s0, 10 * S), end_pts_us=min(s1, 22 * S)
                    ),
                ),
            )
        descriptions.append(
            SegmentDescription(
                segment_id=sid,
                video_id=video_id,
                source_sha256=source_sha,
                time_range=TimeRangeUs(start_pts_us=s0, end_pts_us=s1),
                model_id=COSMOS_MODEL,
                prompt_sha256=COSMOS_INGESTION_PROMPT_SHA256,
                raw_output_sha256=fake_sha(f"cosmos-raw:{i}"),
                summary=meta["d"],
                rigid_subjects=subjects,
                actions=actions,
                visibility=tuple(VisibilityLimit(kind=k, confidence=0.8) for k in meta["vis"]),
                search_terms=meta["terms"],
                uncertainty=(
                    "Synthetic fixture; descriptions authored to match the generator timeline.",
                ),
                confidence=0.85,
                mode=InferenceMode.FIXTURE,
            )
        )
    dump("video_segments.json", segments)
    dump("segment_descriptions.json", descriptions)

    indexed = TimeRangeUs(start_pts_us=0, end_pts_us=duration_us)
    video = SourceVideo.create(
        created_at=ts(1), ingest_state=IngestState.SEARCHABLE, indexed_range=indexed, **common_video
    )
    dump("source_video.json", video)
    partial_range = TimeRangeUs(start_pts_us=0, end_pts_us=windows[11][1])
    video_partial = SourceVideo.create(
        created_at=ts(1),
        ingest_state=IngestState.PARTIAL,
        indexed_range=partial_range,
        **common_video,
    )
    dump("source_video_partial.json", video_partial)

    # ---------------- search evidence ----------------
    query = "Find the blue sedan when its rear plate is most visible"
    plan = SearchPlan(
        semantic_query="blue sedan rear license plate most visible",
        objective_terms=("blue sedan", "rear plate", "most visible"),
        subject_classes=("car", "license_plate"),
    )
    cand_specs = [
        (2, 0.91, 0.75, 1.0, 1.0),
        (1, 0.86, 0.5, 1.0, 1.0),
        (3, 0.71, 0.25, 0.6, 1.0),
        (7, 0.38, 0.0, 0.4, 0.0),
        (6, 0.33, 0.0, 0.0, 0.0),
        (10, 0.12, 0.0, 0.0, 0.0),
    ]
    candidates = []
    w = policy.search.weights
    scored = []
    for rank, (ordinal, cos, lex, detm, vis) in enumerate(cand_specs, start=1):
        comp = ScoreComponents(
            cosine=cos, lexical_overlap=lex, detection_match=detm, visibility_match=vis
        )
        score = round(
            w.cosine * cos
            + w.lexical_overlap * lex
            + w.detection_match * detm
            + w.visibility_match * vis,
            6,
        )
        scored.append((ordinal, comp, score, rank, cos))
    final = sorted(scored, key=lambda t: (-t[2], t[0]))
    # segment 1 [6,14] and 2 [12,20] have time IoU 2/14 < 0.6, so no collapse here.
    final_rank = {o: r for r, (o, *_rest) in enumerate(final, start=1)}
    for ordinal, comp, score, vrank, cos in scored:
        candidates.append(
            SearchCandidate(
                segment_id=segment_id(video_id, ordinal),
                vector_rank=vrank,
                similarity=cos,
                components=comp,
                score=score,
                final_rank=final_rank[ordinal],
            )
        )
    results = []
    for r, (ordinal, comp, score, _vr, _c) in enumerate(final[:5], start=1):
        seg = segments[ordinal]
        ev = seg.evidence_detection_ids
        if ev:
            expl = (
                f"Segment {seg.start_pts_us / S:.1f}-{seg.end_pts_us / S:.1f} s: {seg.description} "
                f"{len(ev)} license_plate detection(s) cited."
            )
        else:
            expl = (
                f"Segment {seg.start_pts_us / S:.1f}-{seg.end_pts_us / S:.1f} s: {seg.description}"
            )
        results.append(
            SearchResult(
                rank=r,
                segment_id=seg.segment_id,
                video_id=video_id,
                source_sha256=source_sha,
                score=score,
                components=comp,
                start_pts_us=seg.start_pts_us,
                end_pts_us=seg.end_pts_us,
                start_frame=seg.start_frame,
                end_frame=seg.end_frame,
                thumbnail_uri=seg.thumbnail_uri,
                description=seg.description or "",
                detected_classes=seg.detected_classes,
                evidence_detection_ids=ev,
                explanation=expl[:600],
                explanation_source=ExplanationSource.TEMPLATE,
                explanation_input_hash=hashlib.sha256(
                    canonical_json(seg.canonical_payload())
                ).hexdigest(),
            )
        )
    search = SearchEvidence.create(
        created_at=ts(120),
        search_id=det_uuid7("search:ok", 120_000),
        case_id=case_id,
        video_id=video_id,
        query=query,
        query_plan=plan,
        planner_model_id=PLANNER_MODEL,
        embedding_model_id=EMBED_MODEL,
        reasoner_model_id=None,
        status=SearchStatus.OK,
        mode=InferenceMode.FIXTURE,
        indexed_range=indexed,
        candidates=tuple(candidates),
        results=tuple(results),
        latency_ms=42,
        correlation_id=det_uuid7("corr:search", 120_000),
    )
    dump("search_evidence.json", search)
    clar = SearchEvidence.create(
        created_at=ts(130),
        search_id=det_uuid7("search:clarify", 130_000),
        case_id=case_id,
        video_id=video_id,
        query="Who is the guilty driver and why did they flee?",
        query_plan=SearchPlan(
            semantic_query="",
            needs_clarification=True,
            filtered_terms=("who", "guilty", "driver", "why"),
            policy_reason_codes=(ReasonCode.QUERY_POLICY_FILTERED,),
        ),
        planner_model_id=PLANNER_MODEL,
        embedding_model_id=EMBED_MODEL,
        reasoner_model_id=None,
        status=SearchStatus.NEEDS_CLARIFICATION,
        mode=InferenceMode.FIXTURE,
        indexed_range=indexed,
        candidates=(),
        results=(),
        latency_ms=3,
        correlation_id=det_uuid7("corr:clarify", 130_000),
    )
    dump("search_evidence_needs_clarification.json", clar)

    # ---------------- tracks ----------------
    target_n, donors_n = 417, (409, 424)
    track_id = det_uuid7("track:confirmed", 200_000)
    obs = []
    for n in det_frames:
        d = det_by_frame[n]
        rejected = n == 405
        obs.append(
            TrackObservation(
                frame_id=d.frame_id,
                pts_us=d.pts_us,
                bbox_px=d.bbox_px,
                source=ObservationSource.DETECTOR,
                detection_id=d.detection_id,
                confidence=d.confidence,
                accepted=not rejected,
                reason_code=ReasonCode.IDENTITY_GEOMETRY_MISMATCH if rejected else None,
            )
        )
    target_pts = pts_us(target_n)
    accepted = [o for o in obs if o.accepted]
    track = Track.create(
        created_at=ts(200),
        track_id=track_id,
        case_id=case_id,
        video_id=video_id,
        subject_type=SubjectType.LICENSE_PLATE,
        seed_frame_id=frame_id(video_id, target_n),
        seed_bbox_px=measured[target_n],
        seed_detection_id=det_by_frame[target_n].detection_id,
        tracker_version="bytetrack-fixture-1",
        detector_model_id=YOLO_MODEL,
        window_start_us=target_pts - 2 * S,
        window_end_us=target_pts + 2 * S,
        state=TrackState.CONFIRMED,
        mean_confidence=round(sum(o.confidence for o in accepted) / len(accepted), 4),
        continuity_score=0.94,
        confirmed=True,
        detector_observation_count=len(accepted),
        observations=tuple(obs),
        reason_codes=(ReasonCode.TRACK_CONFIRMED,),
        mode=InferenceMode.FIXTURE,
    )
    dump("track_confirmed.json", track)
    nc_obs = tuple(o for o in obs if o.pts_us >= pts_us(423))
    track_nc = Track.create(
        created_at=ts(210),
        track_id=det_uuid7("track:not-confirmed", 210_000),
        case_id=case_id,
        video_id=video_id,
        subject_type=SubjectType.LICENSE_PLATE,
        seed_frame_id=frame_id(video_id, 426),
        seed_bbox_px=measured.get(426, det_by_frame[426].bbox_px),
        seed_detection_id=det_by_frame[426].detection_id,
        tracker_version="bytetrack-fixture-1",
        detector_model_id=YOLO_MODEL,
        window_start_us=pts_us(423),
        window_end_us=pts_us(429),
        state=TrackState.NOT_CONFIRMED,
        mean_confidence=0.72,
        continuity_score=0.4,
        confirmed=False,
        detector_observation_count=sum(1 for o in nc_obs if o.accepted),
        observations=nc_obs,
        reason_codes=(ReasonCode.TRACK_NOT_CONFIRMED,),
        mode=InferenceMode.FIXTURE,
    )
    dump("track_not_confirmed.json", track_nc)

    # ---------------- reconstruction artifacts (contract mocks) ----------------
    ART.mkdir(parents=True, exist_ok=True)
    target = decode_frame(target_n)
    donor_imgs = {n: decode_frame(n) for n in donors_n}
    tx1, ty1, tx2, ty2 = measured[target_n]
    H, W = target.shape[:2]
    result = target.copy()
    cls_map = np.zeros((H, W), dtype=np.uint8)
    src_idx = np.zeros((H, W), dtype=np.uint16)
    yy, xx = np.mgrid[0:H, 0:W]
    src_x = xx.astype(np.float32)
    src_y = yy.astype(np.float32)
    shifts = {n: measured[target_n][0] - measured[n][0] for n in donors_n}
    tiles_x = list(range(tx1, tx2 - 7, 8))
    borrowed = 0
    for col, x0 in enumerate(tiles_x):
        y0 = ty1 + 8
        lut_index, n = (1, donors_n[0]) if col < len(tiles_x) // 2 else (2, donors_n[1])
        dx = shifts[n]
        result[y0 : y0 + 8, x0 : x0 + 8] = donor_imgs[n][y0 : y0 + 8, x0 - dx : x0 - dx + 8]
        cls_map[y0 : y0 + 8, x0 : x0 + 8] = 1
        src_idx[y0 : y0 + 8, x0 : x0 + 8] = lut_index
        src_x[y0 : y0 + 8, x0 : x0 + 8] -= dx
        borrowed += 64
    Image.fromarray(target).save(ART / "target_f417.png", optimize=True)
    Image.fromarray(result).save(ART / "result.png", optimize=True)
    for n, img in donor_imgs.items():
        Image.fromarray(img).save(ART / f"donor_f{n}.png", optimize=True)
    buf = io.BytesIO()
    np.savez_compressed(
        buf, **{"class": cls_map, "source_index": src_idx, "source_x": src_x, "source_y": src_y}
    )
    (ART / "provenance.npz").write_bytes(buf.getvalue())
    result_sha = file_sha(ART / "result.png")
    prov_sha = file_sha(ART / "provenance.npz")

    run_id = det_uuid7("run:succeeded", 300_000)
    decision_specs = [
        (
            ReasonCode.SOURCE_HASH_VERIFIED,
            PolicyStage.INPUT,
            "source",
            PolicyOutcome.ACCEPT,
            "Source re-hash matched ingest hash",
            source_sha[:12],
            "==",
            source_sha[:12],
            None,
            None,
        ),
        (
            ReasonCode.TRACK_CONFIRMED,
            PolicyStage.TRACK,
            track_id,
            PolicyOutcome.ACCEPT,
            "Detector-backed observations meet minimum",
            len(accepted),
            ">=",
            5,
            "observations",
            "track.min_detector_observations",
        ),
        (
            ReasonCode.ALIGNMENT_AKAZE_ACCEPTED,
            PolicyStage.ALIGN,
            frame_id(video_id, 409),
            PolicyOutcome.ACCEPT,
            "AKAZE homography inlier ratio passed",
            0.88,
            ">=",
            0.65,
            "ratio",
            "alignment.min_inlier_ratio",
        ),
        (
            ReasonCode.ALIGNMENT_AKAZE_ACCEPTED,
            PolicyStage.ALIGN,
            frame_id(video_id, 424),
            PolicyOutcome.ACCEPT,
            "AKAZE homography inlier ratio passed",
            0.84,
            ">=",
            0.65,
            "ratio",
            "alignment.min_inlier_ratio",
        ),
        (
            ReasonCode.DONOR_NOT_CLEARER,
            PolicyStage.QUALITY,
            frame_id(video_id, 411),
            PolicyOutcome.REJECT,
            "Donor quality gain below minimum",
            0.04,
            ">=",
            0.10,
            "quality",
            "donor.min_quality_gain",
        ),
        (
            ReasonCode.BORROW_TILE_ACCEPTED,
            PolicyStage.FUSE,
            "tiles",
            PolicyOutcome.ACCEPT,
            "Borrowed tiles improved sharpness",
            borrowed // 64,
            ">=",
            1,
            "tiles",
            "fusion.min_sharpness_improvement",
        ),
        (
            ReasonCode.PROVENANCE_COMPLETE,
            PolicyStage.PROVENANCE,
            run_id,
            PolicyOutcome.ACCEPT,
            "Every output pixel resolves",
            1.0,
            "==",
            1.0,
            "fraction",
            "integrity.required_provenance_coverage",
        ),
    ]

    def decisions_for(
        rid: str, specs: list[tuple[Any, ...]], label: str, t0: float
    ) -> list[PolicyDecision]:
        out = []
        for seq, (code, stage, subj, outcome, reason, observed, op, thr, units, key) in enumerate(
            specs
        ):
            out.append(
                PolicyDecision.create(
                    created_at=ts(t0 + seq * 0.1),
                    decision_id=det_uuid7(f"{label}:dec:{seq}", int(t0 * 1000) + seq),
                    run_id=rid,
                    sequence=seq,
                    rule_code=code,
                    stage=stage,
                    subject_ref=subj,
                    outcome=outcome,
                    reason=reason,
                    observed=observed,
                    operator=op,
                    threshold=thr,
                    units=units,
                    policy_key=key,
                )
            )
        return out

    decisions = decisions_for(run_id, decision_specs, "run-ok", 300)
    dump("policy_decisions_succeeded.json", decisions)
    dec_ids = tuple(d.decision_id for d in decisions)
    lut = (
        SourceLutEntry(
            index=0,
            frame_id=frame_id(video_id, target_n),
            frame_number=target_n,
            pts_us=target_pts,
            role=SourceRole.TARGET,
            alignment_method=AlignmentMethod.IDENTITY,
            interpolation=Interpolation.IDENTITY,
        ),
        *[
            SourceLutEntry(
                index=i,
                frame_id=frame_id(video_id, n),
                frame_number=n,
                pts_us=pts_us(n),
                role=SourceRole.DONOR,
                transform_id=f"h_{n}",
                alignment_method=AlignmentMethod.AKAZE_HOMOGRAPHY,
                matrix=(1.0, 0.0, float(shifts[n]), 0.0, 1.0, 0.0, 0.0, 0.0, 1.0),
                interpolation=Interpolation.LANCZOS4,
                color_gain=(1.0, 1.0, 1.0),
                color_bias=(0.0, 0.0, 0.0),
                decision_ids=(dec_ids[1 + i],),
            )
            for i, n in enumerate(donors_n, start=1)
        ],
    )
    total = H * W
    subj = (tx2 - tx1) * (ty2 - ty1)
    pct = CoveragePct(
        ORIGINAL=round(100 * (total - borrowed) / total, 4),
        BORROWED=round(100 * borrowed / total, 4),
        GENERATED_BLEND=0.0,
    )
    spct = CoveragePct(
        ORIGINAL=round(100 * (subj - borrowed) / subj, 4),
        BORROWED=round(100 * borrowed / subj, 4),
        GENERATED_BLEND=0.0,
    )
    prov_base = f"derived/{video_id}/reconstruction/{run_id}"
    provenance = PixelProvenance.create(
        created_at=ts(310),
        run_id=run_id,
        width_px=W,
        height_px=H,
        subject_bbox_px=measured[target_n],
        class_map_uri=f"{prov_base}/provenance.npz",
        source_index_uri=f"{prov_base}/provenance.npz",
        source_xy_uri=f"{prov_base}/provenance.npz",
        source_lut=lut,
        coverage_counts=CoverageCounts(
            ORIGINAL=total - borrowed, BORROWED=borrowed, GENERATED_BLEND=0
        ),
        coverage_pct=pct,
        subject_coverage_pct=spct,
        coverage_complete=True,
        artifact_sha256=prov_sha,
    )
    dump("pixel_provenance.json", provenance)
    comps = dict(
        supported_coverage=1.0,
        mean_source_confidence=0.86,
        mean_alignment_confidence=0.93,
        track_continuity=0.94,
        audit_completeness=1.0,
        semantic_generated_pct=0.0,
    )
    integrity = IntegrityScore(score_0_100=integrity_score_0_100(**comps), **comps)
    a_result, a_prov, a_clip = (
        det_uuid7(f"asset:{k}", 310_000 + i) for i, k in enumerate(("result", "prov", "clip"))
    )
    for aid, kind, name, mt, sha, size, ne in (
        (
            a_result,
            AssetKind.RESULT_PNG,
            "result.png",
            "image/png",
            result_sha,
            (ART / "result.png").stat().st_size,
            False,
        ),
        (
            a_prov,
            AssetKind.PROVENANCE_NPZ,
            "provenance.npz",
            "application/octet-stream",
            prov_sha,
            (ART / "provenance.npz").stat().st_size,
            False,
        ),
    ):
        assets.append(
            AssetRef(
                asset_id=aid,
                case_id=case_id,
                kind=kind,
                storage_uri=f"fixtures/contracts/artifacts/{name}",
                media_type=mt,
                byte_length=size,
                sha256=sha,
                non_evidentiary=ne,
                created_at=ts(310),
            )
        )
    run_ok = ReconstructionRun.create(
        created_at=ts(300),
        run_id=run_id,
        case_id=case_id,
        video_id=video_id,
        track_id=track_id,
        target_frame_id=frame_id(video_id, target_n),
        target_pts_us=target_pts,
        target_bbox_px=measured[target_n],
        state=ReconstructionState.SUCCEEDED,
        config_sha256=policy.config_sha256,
        iteration_count=2,
        accepted_donor_frame_ids=tuple(frame_id(video_id, n) for n in donors_n),
        result_png_uri=f"asset://{a_result}",
        inspection_clip_uri=None,
        provenance_uri=f"asset://{a_prov}",
        provenance=ProvenanceSummary(
            coverage_pct=pct, subject_coverage_pct=spct, coverage_complete=True, source_lut=lut
        ),
        result_png_sha256=result_sha,
        provenance_sha256=prov_sha,
        policy_decision_ids=dec_ids,
        integrity=integrity,
        uncertainty=(
            "Result may remain blurry where no compatible donor was clearer.",
            "Contract mock artifact: pixels copied by recorded translation, not Probity output.",
            "Verified cached inference (fixture mode).",
        ),
        mode=InferenceMode.FIXTURE,
        started_at=ts(300),
        finished_at=ts(302.5),
    )
    dump("reconstruction_run_succeeded.json", run_ok)

    run_ref_id = det_uuid7("run:refused", 400_000)
    ref_specs = [
        (
            ReasonCode.SOURCE_HASH_VERIFIED,
            PolicyStage.INPUT,
            "source",
            PolicyOutcome.ACCEPT,
            "Source re-hash matched ingest hash",
            source_sha[:12],
            "==",
            source_sha[:12],
            None,
            None,
        ),
        (
            ReasonCode.DONOR_OBSTRUCTED,
            PolicyStage.PREFLIGHT,
            frame_id(video_id, 411),
            PolicyOutcome.REJECT,
            "Occluded fraction above limit",
            0.31,
            "<=",
            0.15,
            "fraction",
            "donor.max_occluded_fraction",
        ),
        (
            ReasonCode.ALIGNMENT_FAILED,
            PolicyStage.ALIGN,
            frame_id(video_id, 420),
            PolicyOutcome.REJECT,
            "Inlier ratio below gate after one ECC fallback",
            0.41,
            ">=",
            0.65,
            "ratio",
            "alignment.min_inlier_ratio",
        ),
        (
            ReasonCode.INSUFFICIENT_COMPATIBLE_DONORS,
            PolicyStage.RANK,
            run_ref_id,
            PolicyOutcome.REJECT,
            "Fewer than two donors passed alignment and obstruction gates",
            1,
            ">=",
            2,
            "donors",
            "donor.min_count",
        ),
    ]
    ref_decisions = decisions_for(run_ref_id, ref_specs, "run-refused", 400)
    dump("policy_decisions_refused.json", ref_decisions)
    run_refused = ReconstructionRun.create(
        created_at=ts(400),
        run_id=run_ref_id,
        case_id=case_id,
        video_id=video_id,
        track_id=track_id,
        target_frame_id=frame_id(video_id, 414),
        target_pts_us=pts_us(414),
        target_bbox_px=measured.get(414, det_by_frame[414].bbox_px),
        state=ReconstructionState.REFUSED,
        config_sha256=policy.config_sha256,
        iteration_count=0,
        accepted_donor_frame_ids=(frame_id(video_id, 409),),
        policy_decision_ids=tuple(d.decision_id for d in ref_decisions),
        refusal_reasons=(ReasonCode.INSUFFICIENT_COMPATIBLE_DONORS,),
        uncertainty=("No defensible enhancement produced; the original frame is unchanged.",),
        mode=InferenceMode.FIXTURE,
        started_at=ts(400),
        finished_at=ts(401.2),
    )
    dump("reconstruction_run_refused.json", run_refused)
    run_failed = ReconstructionRun.create(
        created_at=ts(450),
        run_id=det_uuid7("run:failed", 450_000),
        case_id=case_id,
        video_id=video_id,
        track_id=track_id,
        target_frame_id=frame_id(video_id, target_n),
        target_pts_us=target_pts,
        target_bbox_px=measured[target_n],
        state=ReconstructionState.FAILED,
        config_sha256=policy.config_sha256,
        iteration_count=0,
        accepted_donor_frame_ids=(),
        policy_decision_ids=(),
        refusal_reasons=(),
        uncertainty=("Run failed before producing artifacts; see job error.",),
        mode=InferenceMode.FIXTURE,
        started_at=ts(450),
        finished_at=ts(450.4),
    )
    dump("reconstruction_run_failed.json", run_failed)

    bx, by = tiles_x[0] + 3, ty1 + 8 + 3
    dx0 = shifts[donors_n[0]]
    origin = PixelOrigin(
        run_id=run_id,
        x=bx,
        y=by,
        provenance_class="BORROWED",
        source_index=1,
        source_frame_id=frame_id(video_id, donors_n[0]),
        source_pts_us=pts_us(donors_n[0]),
        source_x=float(bx - dx0),
        source_y=float(by),
        transform_id=f"h_{donors_n[0]}",
        alignment_method=AlignmentMethod.AKAZE_HOMOGRAPHY,
        color_gain=(1.0, 1.0, 1.0),
        color_bias=(0.0, 0.0, 0.0),
        decision_ids=(dec_ids[2],),
    )
    dump("pixel_origin_borrowed.json", origin)

    # ---------------- reviews and report ----------------
    approve = HumanReview.create(
        created_at=ts(500),
        review_id=det_uuid7("review:approve", 500_000),
        run_id=run_id,
        reviewer_alias="analyst-1",
        decision=ReviewDecision.APPROVE,
        reason_code=None,
        comment="Inspected donors and provenance overlay.",
        reviewed_result_sha256=result_sha,
        reviewed_provenance_sha256=prov_sha,
    )
    veto = HumanReview.create(
        created_at=ts(510),
        review_id=det_uuid7("review:veto", 510_000),
        run_id=run_id,
        reviewer_alias="analyst-2",
        decision=ReviewDecision.VETO,
        reason_code=VetoReason.MISALIGNMENT,
        comment="Right-most borrowed tile edge appears offset by one pixel.",
        reviewed_result_sha256=result_sha,
        reviewed_provenance_sha256=prov_sha,
    )
    dump("human_review_approve.json", approve)
    dump("human_review_veto.json", veto)
    a_html, a_json = (
        det_uuid7("asset:report-html", 600_000),
        det_uuid7("asset:report-json", 600_001),
    )
    for aid, kind, name, mt in (
        (a_html, AssetKind.REPORT_HTML, "report.html", "text/html"),
        (a_json, AssetKind.REPORT_JSON, "report.json", "application/json"),
    ):
        assets.append(
            AssetRef(
                asset_id=aid,
                case_id=case_id,
                kind=kind,
                storage_uri=f"derived/{video_id}/report/{det_uuid7('report', 600_000)}/{name}",
                media_type=mt,
                byte_length=4096,
                sha256=fake_sha(name),
                non_evidentiary=False,
                created_at=ts(600),
            )
        )
    report = EvidenceReport.create(
        created_at=ts(600),
        report_id=det_uuid7("report", 600_000),
        case_id=case_id,
        run_id=run_id,
        review_id=approve.review_id,
        source_sha256=source_sha,
        source_sha256_verified_at_export=source_sha,
        source_verified=True,
        html_uri=f"asset://{a_html}",
        json_uri=f"asset://{a_json}",
        bundle_sha256=fake_sha("bundle"),
        generated_at=ts(601),
        draft_model_id=None,
        mode=InferenceMode.FIXTURE,
        limitations=(
            "Research/demo prototype - not for legal conclusions.",
            "Application-level immutability only; not formal chain of custody.",
            "Verified cached inference (fixture mode) supplied search and tracking.",
            "Codec loss already present in the source cannot be reversed.",
        ),
    )
    dump("evidence_report.json", report)
    assets.insert(
        0,
        AssetRef(
            asset_id=asset_source,
            case_id=case_id,
            kind=AssetKind.SOURCE_VIDEO,
            storage_uri=storage_uri,
            media_type="video/mp4",
            byte_length=byte_length,
            sha256=source_sha,
            non_evidentiary=False,
            created_at=ts(1),
        ),
    )
    dump("asset_refs.json", assets)

    # ---------------- job views ----------------
    corr = det_uuid7("corr:jobs", 50_000)
    seg_ids = [s.segment_id for s in segments]

    def job(
        label: str, kind: JobKind, subject: str, state: JobState, t: float, **kw: Any
    ) -> JobView:
        terminal = state in {
            JobState.SUCCEEDED,
            JobState.PARTIAL,
            JobState.REFUSED,
            JobState.FAILED,
            JobState.CANCELLED,
        }
        if state in {JobState.CANCELLING, JobState.CANCELLED}:
            kw.setdefault("cancel_requested_at", ts(t + 1))
        return JobView.create(
            created_at=ts(t),
            job_id=det_uuid7(f"job:{label}", int(t * 1000)),
            kind=kind,
            case_id=case_id,
            subject_id=subject,
            state=state,
            mode=InferenceMode.FIXTURE,
            correlation_id=corr,
            updated_at=ts(t + 2),
            started_at=ts(t + 0.5) if state not in {JobState.CREATED, JobState.QUEUED} else None,
            finished_at=ts(t + 3) if terminal else None,
            **kw,
        )

    n_seg = len(segments)
    jobs = [
        job("ingest-created", JobKind.INGEST, video_id, JobState.CREATED, 10, total_units=n_seg),
        job("ingest-queued", JobKind.INGEST, video_id, JobState.QUEUED, 11, total_units=n_seg),
        job(
            "ingest-running",
            JobKind.INGEST,
            video_id,
            JobState.RUNNING,
            12,
            stage=JobStage.DESCRIBE,
            completed_units=5,
            total_units=n_seg,
        ),
        job(
            "ingest-succeeded",
            JobKind.INGEST,
            video_id,
            JobState.SUCCEEDED,
            13,
            stage=JobStage.INDEX,
            completed_units=n_seg,
            total_units=n_seg,
        ),
        job(
            "ingest-partial",
            JobKind.INGEST,
            video_id,
            JobState.PARTIAL,
            14,
            stage=JobStage.INDEX,
            completed_units=12,
            total_units=n_seg,
            partial=PartialCoverage(
                committed_segment_ids=tuple(seg_ids[:12]),
                indexed_ranges=(partial_range,),
                failed_segment_ids=tuple(seg_ids[12:]),
            ),
        ),
        job(
            "ingest-failed",
            JobKind.INGEST,
            video_id,
            JobState.FAILED,
            15,
            stage=JobStage.EXTRACT,
            completed_units=0,
            total_units=n_seg,
            error=JobError(
                code=ErrorCode.WORKER_INTERRUPTED,
                message="Worker lease expired; the job was interrupted. Retry with the original idempotent input.",
                retryable=True,
            ),
        ),
        job(
            "ingest-sponsor-timeout",
            JobKind.INGEST,
            video_id,
            JobState.FAILED,
            16,
            stage=JobStage.DESCRIBE,
            completed_units=0,
            total_units=n_seg,
            error=JobError(
                code=ErrorCode.SPONSOR_TIMEOUT,
                message="Cosmos retry budget exhausted. Continue with verified demo cache?",
                retryable=True,
            ),
        ),
        job(
            "ingest-cancelling",
            JobKind.INGEST,
            video_id,
            JobState.CANCELLING,
            17,
            stage=JobStage.EMBED,
            completed_units=7,
            total_units=n_seg,
        ),
        job(
            "ingest-cancelled",
            JobKind.INGEST,
            video_id,
            JobState.CANCELLED,
            18,
            stage=JobStage.EMBED,
            completed_units=7,
            total_units=n_seg,
            partial=PartialCoverage(
                committed_segment_ids=tuple(seg_ids[:7]),
                indexed_ranges=(TimeRangeUs(start_pts_us=0, end_pts_us=windows[6][1]),),
            ),
        ),
        job(
            "track-succeeded",
            JobKind.TRACK,
            track_id,
            JobState.SUCCEEDED,
            20,
            stage=JobStage.TRACK,
            completed_units=1,
            total_units=1,
        ),
        job(
            "track-refused",
            JobKind.TRACK,
            track_nc.track_id,
            JobState.REFUSED,
            21,
            stage=JobStage.TRACK,
            completed_units=1,
            total_units=1,
            refusal_reasons=(ReasonCode.TRACK_NOT_CONFIRMED,),
        ),
        job(
            "recon-running",
            JobKind.RECONSTRUCT,
            run_id,
            JobState.RUNNING,
            30,
            stage=JobStage.ALIGN,
            completed_units=2,
            total_units=4,
        ),
        job(
            "recon-succeeded",
            JobKind.RECONSTRUCT,
            run_id,
            JobState.SUCCEEDED,
            31,
            stage=JobStage.FUSE,
            completed_units=4,
            total_units=4,
        ),
        job(
            "recon-refused",
            JobKind.RECONSTRUCT,
            run_ref_id,
            JobState.REFUSED,
            32,
            stage=JobStage.ALIGN,
            completed_units=3,
            total_units=4,
            refusal_reasons=(ReasonCode.INSUFFICIENT_COMPATIBLE_DONORS,),
        ),
        job(
            "recon-failed",
            JobKind.RECONSTRUCT,
            run_failed.run_id,
            JobState.FAILED,
            33,
            stage=JobStage.ALIGN,
            completed_units=0,
            total_units=4,
            error=JobError(
                code=ErrorCode.SOURCE_HASH_MISMATCH,
                message="Source bytes no longer match the ingest hash; reconstruction blocked.",
                retryable=False,
            ),
        ),
        job(
            "report-succeeded",
            JobKind.REPORT,
            report.report_id,
            JobState.SUCCEEDED,
            40,
            stage=JobStage.REPORT,
            completed_units=1,
            total_units=1,
        ),
    ]
    dump("job_views.json", jobs)

    # ---------------- demo fixture catalog ----------------
    # Paths are relative to fixtures/demo/. Search fixture files under fixtures/demo/search/ are
    # appended by the coordinator when that workstream is integrated.
    files: list[FixtureFile] = []
    catalog = FixtureCatalog(
        fixtures=(
            FixtureManifest(
                fixture_id=FIXTURE_ID,
                display_name="Synthetic plate/sign street clip (90 s)",
                source=FixtureSource(
                    path="source/demo-plate-90s.mp4",
                    sha256=source_sha,
                    byte_length=byte_length,
                    duration_us=duration_us,
                    license_note=LICENSE,
                    synthetic=True,
                    generator="scripts/generate_demo_video.py",
                ),
                policy_config_sha256=policy.config_sha256,
                ingestion_prompt_sha256=COSMOS_INGESTION_PROMPT_SHA256,
                models=(
                    FixtureModelRef(role="cosmos_describe", model_id=COSMOS_MODEL),
                    FixtureModelRef(
                        role="cosmos_embed", model_id=EMBED_MODEL, embedding_dimension=64
                    ),
                    FixtureModelRef(
                        role="yolo_detect",
                        model_id=YOLO_MODEL,
                        model_sha256=fake_sha("yolo-weights"),
                    ),
                    FixtureModelRef(role="wandb_plan", model_id=PLANNER_MODEL),
                    FixtureModelRef(role="wandb_explain", model_id=REASONER_MODEL),
                ),
                files=tuple(files),
                created_at=ts(0),
            ),
        )
    )
    (ROOT / "fixtures/demo/manifest.json").write_text(
        json.dumps(catalog.model_dump(mode="json"), indent=2) + "\n"
    )
    print(
        f"source_sha256={source_sha} frames={frame_count} duration_us={duration_us} segments={n_seg}"
    )
    print(
        f"plate bbox f417={measured[target_n]} shifts={shifts} borrowed_px={borrowed} integrity={integrity.score_0_100}"
    )


if __name__ == "__main__":
    main()
